- name: Get cluster name
  ansible.builtin.command: terraform output cluster_name
  args:
    chdir: ../terraform
  register: cluster_name

- name: Get AWS Ingress service account name
  ansible.builtin.command: terraform output elb_ingress_controller_service_account_role_arn
  args:
    chdir: ../terraform
  register: alb_ingress_service_account_role_arn

- name: Generate AWS Ingress Service Account yaml
  template: 
    src: alb-ingress-service-account.j2
    dest: /tmp/alb-ingress-service-account.yml

- name: Deploy AWS Ingress Service Account
  ansible.builtin.command: kubectl --kubeconfig  ~/.kube/{{ cluster_name.stdout }} apply -f /tmp/alb-ingress-service-account.yml

- name: Describe AWS Ingress Service Account
  ansible.builtin.command: kubectl --kubeconfig ~/.kube/{{ cluster_name.stdout }} describe sa aws-load-balancer-controller -n kube-system
  register: aws_load_balancer_controller_sa

- ansible.builtin.debug:
    msg:
    - "{{ aws_load_balancer_controller_sa.stdout }}"

